### ISSUE TITLE
Create Redux CRA+TS template

### ISSUE THREAD

**Issue by markerikson** [reduxjs/cra-template-redux-typescript#1]
Now that we have the plain JS template at https://github.com/reduxjs/cra-template-redux published as 1.0.0, we can start working on the TS template.

Based on the process we used for that template, seems like we should:

- Create a PR here that adds the entire contents of the standard CRA TS template, minus the version numbers, and merge that in
- Create a PR that clears out the source code contents (or possibly just skip all the source in the first PR)
- Create a PR that ports the code from the JS template, and converts it all to TS.

@BenLorantfy indicated he was interested in doing this one too ( https://github.com/reduxjs/cra-template-redux/pull/1#issuecomment-587266306 ) , but could probably get a couple folks collaborating here.

**Comment by lukyth** [comment]
I'm interested to help as well. Please let me know if there's anything I can do! @BenLorantfy

**Comment by markerikson** [comment]
@lukyth : thanks!  As a starting point, can you file a PR to add the entire contents of the existing CRA+TS template from https://github.com/facebook/create-react-app/tree/master/packages/cra-template-typescript ?  Move the content to the root of the repo, and go ahead and remove all source files exist for `index.tsx`.  (Maybe just throw in a tiny `const App = () => <div>Hello</div>` in `index.tsx` as a placeholder.)

See the PR where we added the default JS template as an example:

https://github.com/reduxjs/cra-template-redux/pull/2

**Comment by BenLorantfy** [comment]
Yeah if someone could create a PR with the contents of the default CRA+TS template that would be helpful so we can see the changes between the default CRA+TS template and the Redux+TS template

**Comment by lukyth** [comment]
>  can you file a PR to add the entire contents of the existing CRA+TS template

Let me take care of that :)

**Comment by lukyth** [comment]
Do you want me to help with bringing content from `cra-template-redux` over here and convert it to TS? @BenLorantfy

**Comment by BenLorantfy** [comment]
I'm working on that right now

**Comment by nickmccurdy** [comment]
I think this is done
