### ISSUE TITLE
`AppThunk` pattern can't infer return type of thunk

### ISSUE THREAD

**Issue by ProdigySim** [reduxjs/cra-template-redux-typescript#17]
Using the AppThunk type, I may write some thunk that returns a promise:

```ts
export const incrementAsync = (amount: number): AppThunk => async dispatch => {
  dispatch(incrementByAmount(amount))
  return await Promise.resolve(amount);
};
```
But, `AppThunk` does not seem to infer the return type here, and just uses `void`. So, `incrementAsync` gets a type of `(amount: number) => AppThunk<void>`.

Using a classic signature like 
```ts
export const incrementAsync = (amount: number) => async (dispatch: Dispatch) => {
  dispatch(incrementByAmount(amount))
  return await Promise.resolve(amount);
};
```
gives us a type for `incrementAsync` of `const incrementAsync: (amount: number) => (dispatch: Dispatch) => Promise<number>` which infers the thunk return type properly.

Probably consider this more of a feature request, but it would be neat if there were a pattern that could support both the return type & parameter type inference here.

**Comment by markerikson** [comment]
Yeah, it's a bit of a tradeoff.  You _should_ be able to do `AppThunk<Promise<MyData>>` for those cases where you need the promise result.

That said, this really isn't an issue that's specific to the template itself - it's more about documenting ways to use thunks with TS, which is better suited for the core Redux repo.  If you can file a PR to update the core docs, I'd appreciate it.  Thanks!

**Comment by ProdigySim** [comment]
You could define another helper like

```ts
function createThunk<T>(thunk: AppThunk<T>) { return thunk; }
```
Which seems to convince Typescript to infer the return type properly
