### ISSUE TITLE
Add .eslintrc to the template project

### ISSUE THREAD

**Issue by mauriciord** [reduxjs/cra-template-redux-typescript#18]
You could add a `.eslintrc` to the template.

**Comment by nickmccurdy** [comment]
This is already using `eslint-config-react-app`, which I think is already a great starting point for React JS/TS apps, and I don't think much else is needed for Redux. The template is also already formatted with Prettier to keep it consistent.

**Comment by markerikson** [comment]
Yeah, CRA has its own linting config already, and [documents how to add your own if desired](https://create-react-app.dev/docs/advanced-configuration).  Nothing for us to add here.
