### ISSUE TITLE
Any explanation on what goes into which folder and why?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [reduxjs/cra-template-redux-typescript#19]

**Comment by markerikson** [comment]
Sorry, not sure what you're asking for here, but I'd suggest reading:

- https://redux.js.org/style-guide/style-guide#structure-files-as-feature-folders-or-ducks
- https://redux.js.org/faq/code-structure#what-should-my-file-structure-look-like-how-should-i-group-my-action-creators-and-reducers-in-my-project-where-should-my-selectors-go
