### ISSUE TITLE
Add redux-dynamic-modules?

### ISSUE THREAD

**Issue by dbartholomae** [reduxjs/cra-template-redux-typescript#20]
Hi there, I would love to add [redux-dynamic-modules](https://redux-dynamic-modules.js.org/#/) to this template, which allows to dynamically add redux logic instead of having to define it all in one central store file. This library made redux really useful as the store doesn't get cluttered with state that isn't currently needed, it makes code more modular and adding it in this template would bring it to the attention of other people using redux.
What do you think? I know that adding more stuff to a template is always problemativ, but as the template already takes an opinionated approach by adding thunk instead of e. g. redux-saga or rxjs it feels to me that this choice would make sense as well.
If there is interest, I could also provide the PR.

**Comment by markerikson** [comment]
That's a neat lib, but we're definitely _not_ going to add anything that complex and opinionated to this template, in the same way that the base CRA template doesn't include Redux, React Router, or anything else on top.
