### ISSUE TITLE
is-promise preventing new project creation.

### ISSUE THREAD

**Issue by o2x7** [reduxjs/cra-template-redux-typescript#22]
[The same issue manifested itself in create-react-app earlier today](https://github.com/facebook/create-react-app/issues/8896).  When you call

`npx create-react-app app --template redux-typescript`

the command fails with the following output

`No valid exports main found for '/Users/blackpanther-ralco/.config/yarn/global/node_modules/is-promise'`

node version: v13.8.0

**Comment by o2x7** [comment]
I guess this is going on in create-react-app still, please ignore as I assume this is due to the node module not this template specifically

**Comment by markerikson** [comment]
Yeah, that's because the problem ultimately prevents CRA itself from installing / running, no matter what template you've told CRA to install with.
