### ISSUE TITLE
cyclic dependecy

### ISSUE THREAD

**Issue by sa1dai** [reduxjs/cra-template-redux-typescript#24]
To create `RootState` we need `store`. To create `store` we need `counterReducer`. To create `counterReducer` we need `RootState`.
Cyclic dependency occured. 

Same applied to `AppThunk`

I removed this error by restructure project: 

before:
counterSlice.ts

after:
slice.ts
selectors.ts
async.ts

**Comment by markerikson** [comment]
TS supports cyclic types just fine, since that's only a compile-time thing.  There's no bug here.

**Comment by nickmccurdy** [comment]
Is it possible that this is referring to cyclic imports (not cyclic types)? I believe that would be an issue with TypeScript.

**Comment by nickmccurdy** [comment]
@markerikson Is it possible that this is referring to cyclic imports (not cyclic types)? I believe that would be an issue with TypeScript.

@sa1dai If you're not sure, it would help to see a Code Sandbox or repository reproducing the issue.

**Comment by nickmccurdy** [comment]
@markerikson Is it possible that this is referring to cyclic imports (not cyclic types)? I believe that would be an issue with TypeScript.

@sa1dai If you're not sure, it would help to see a Code Sandbox or repository reproducing the issue.

**Comment by markerikson** [comment]
Nope, the listed concern is about importing `RootState` back into `counterSlice`, which is to be expected and works fine.

**Comment by sa1dai** [comment]
@nickmccurdy @markerikson 
I think @markerikson is right that it is not the issue. To be completely clear:  I started to integrate template to my project and got [this](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) error. After @markerikson  comment that its not the issue cause of TS, I googled, and found [this](https://github.com/benmosher/eslint-plugin-import/issues/1453) thread where states that it is not the issue and should not be even occur. I am going to use [this](https://github.com/benmosher/eslint-plugin-import/issues/1453#issuecomment-601772647) and overcome error.

**Comment by xpol** [comment]
Use Type-Only Imports introduced by typescript 3.8 in `counterSlice.ts` would fix it.

Change this line:
```typescript
import { AppThunk, RootState } from '../../app/store';
```
to
```typescript
import type { AppThunk, RootState } from '../../app/store';
```
