### ISSUE TITLE
Template seems to be a bit out of date

### ISSUE THREAD

**Issue by ariccio** [reduxjs/cra-template-redux-typescript#40]
The latest versions of cra-template-typescript have some goodies by default, like `web-vitals`, and maybe a few other things (I created my app with this template, and the fancy new jsx transform doesn't seem to be working). They should be ported.

**Comment by markerikson** [comment]
That's very likely. Could you help catalog exactly where the differences are?  Would also appreciate a PR if you have time to file one, both here and in the JS template repo.

**Comment by towfiqi** [comment]
@markerikson line 25 and 58 of `counterslice.ts` file throws  `Object is of type 'unknown'` typescript error.

**Comment by markerikson** [comment]
Should resolved with https://github.com/reduxjs/cra-template-redux-typescript/releases/tag/v2.0.0 .
