### ISSUE TITLE
Argument of type 'AsyncThunkAction<number, number, {}>' is not assignable to parameter of type 'AnyAction'. Property 'type' is missing in type 'AsyncThunkAction<number, number, {}>' but required in type 'AnyAction'. TS2345

### ISSUE THREAD

**Issue by nrayann** [reduxjs/cra-template-redux-typescript#42]
I have a fresh install of `yarn create react-app my-app --template redux-typescript`

The app stop working after install `aws-appsync` with `yarn add aws-appsync`

`incrementAsync` and `incrementIfOdd` could not be dispatched with the custom typed hooks

How to make these methods work with `aws-appsync` installed?

**Comment by markerikson** [comment]
Because this repo is the wrong place to file this issue, you cross-posted it across two different repos, I answered the question in the other issue you filed in the RTK repo, and the real problem is with AWS AppSync and not RTK.
