### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by croraf** [reduxjs/cra-template-redux-typescript#48]
Is it possible to create a npm managed version of the template which would be activated by the flag or something, and documented in the readme.

If this is already possible, please document in the readme.

**Comment by markerikson** [comment]
I'm sorry, I'm afraid I really don't understand what you're asking for here.

**Comment by croraf** [comment]
When you create a project with `npx create-react-app test111 --template redux-typescript` you get a yarn-managed project.

I wanted to have an npm-managed project redux-typescript.



I was not aware that I can use `--use-npm` along with `--template redux-typescript` to get npm-managed project, the same as it is possible with no template create-react-app.

**Comment by markerikson** [comment]
That has nothing to do with this template - it's all controlled by the Create-React-App CLI tool.  It defaults to using Yarn if it's installed.
