### ISSUE TITLE
Outdated Dependancies 

### ISSUE THREAD

**Issue by ar-to** [reduxjs/cra-template-redux-typescript#53]
Noticed this when writing a unit test where I was getting something like in this issue https://github.com/testing-library/react-testing-library/issues/802 when importing:

```react
import { render, screen } from "@testing-library/react";
```

so I ran `yarn upgrade-interactive --latest` and got:

![Screen Shot 2021-10-10 at 3 55 06 AM](https://user-images.githubusercontent.com/23410938/136689332-af55a8e7-eb6d-4f3a-b476-5cfecf9c2ef9.png)

so I picked all to upgrade and it cleared my error right up. Note the issue I linked is set back in 2020!

I recommend updating this package.json https://github.com/reduxjs/cra-template-redux-typescript/blob/master/template.json to reflect the latest versions of these packages.

**Comment by markerikson** [comment]
Yeah, I've been pretty busy and haven't had time to look at the template in a while. Could you file a PR to update things?

**Comment by markerikson** [comment]
Should resolved with https://github.com/reduxjs/cra-template-redux-typescript/releases/tag/v2.0.0 .
