### ISSUE TITLE
PWA not working

### ISSUE THREAD

**Issue by VittorioAccomazzi** [reduxjs/cra-template-redux-typescript#59]
I'm not able to get the service worker registering correctly with this template. Here are the steps to reproduce the problem :

* install the template `npx create-react-app@5.0.0 my-pwa --template redux-typescript`
* edit `index.tsx` to enable the service worker  at line 21 as follow : `serviceWorker.register();`
* build the application `npm run build`
* serve the application with serve : `serve -s build` 

The service workers are not installed, this is visible either setting a breakpoint as well as checking with Chrome's developer tools.

**Comment by VittorioAccomazzi** [comment]
the registration fails at this line:
![image](https://user-images.githubusercontent.com/7923323/147798520-c6a6b502-8c75-4aa4-894b-7815a7ac20ea.png)
and *the reason is that the file `service-worker.js` is not found* and serve just sent the `index.html` file. So the problem is somewhere in the compilation step.

**Comment by markerikson** [comment]
Any serviceworker setup is really part of Create-React-App's config - you might want to check over in that repo.

**Comment by VittorioAccomazzi** [comment]
Thank you @markerikson. Indeed Create-React-App has changed, a solution to this problem is posted [here](https://github.com/facebook/create-react-app/issues/10032#issuecomment-723433217).
