### ISSUE TITLE
Broken.

### ISSUE THREAD

**Issue by learningnewthings** [reduxjs/cra-template-redux-typescript#7]
Installation crashed on both 12.16.1 Lts and 13.10.1 current version of node ( run on nvm )
Crashed on both npx and yarn.
create-react-app --template typescript (the normal one, without redux) works.
create-react-app --template redux also works.

Only this one seems to be broken...

**Comment by markerikson** [comment]
That's because we haven't actually published a real version of this template yet :)  Version 0.0.0 is just a placeholder.
