### ISSUE TITLE
should AppThunk be a generic type

### ISSUE THREAD

**Issue by bugzpodder** [reduxjs/cra-template-redux-typescript#8]
most of the ThunkAction returns void, but sometimes the return value from dispatch is useful.  Generally a promise might be returned and we can chain things, eg:
dispatch(thunkAction()).then(...)

I see that AppThunk is defined as ThunkAction<void,...>.  Should it be something generic like
AppThunk<T> = ThunkAction<T,...>

**Comment by markerikson** [comment]
Whoops.  Yeah, it should be.  Can you file a PR to update it?  See https://redux.js.org/recipes/usage-with-typescript#usage-with-redux-thunk .
